// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 ninesix-ai studio

namespace Vonvert.Engine.ProceduralAudio;



/// <summary>

/// Defines the source type of a sound effect.

/// </summary>

public enum SoundSourceType

{

    /// <summary>Procedurally generated by <see cref="SoundGenerator"/>.</summary>

    Generated,



    /// <summary>Imported from an external audio file (MP3/WAV).</summary>

    File

}



/// <summary>

/// Immutable descriptor for a single sound effect.

/// </summary>

/// <param name="Id">Unique identifier, e.g. "kick".</param>

/// <param name="Name">Display name, e.g. "Kick".</param>

/// <param name="Category">Category group, e.g. "Drums".</param>

/// <param name="Emoji">Emoji icon for display.</param>

/// <param name="SourceType">Whether this sound is generated or imported from a file.</param>

public record SoundDefinition(

    string Id,

    string Name,

    string Category,

    string Emoji,

    SoundSourceType SourceType

);

